version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  maven/test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

